//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSosyalMedya
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Link { get; set; }
        public string ikon { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
